
[window]
padding = { x = 6, y = 4 }
opacity = 0.4
# I think labwc does not support blur
# blur = true


[font]
normal = { family = "ZedMono Nerd Font", style = "Regular" }
size = 12.0

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[general]
live_config_reload = true
